name: Close inactive issues
on:
  workflow_dispatch:
  schedule:
    - cron: "25 12 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          days-before-issue-stale: 360
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: ":warning: This issue is stale because it has been open for 360 days with no activity. Please chime in if you want to keep it alive."
          close-issue-message: ":no_entry: This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: 360
          days-before-pr-close: 14
          stale-pr-label: "stale"
          stale-pr-message: ":warning: This pull request is stale because it has been open for 360 days with no activity. Please chime in if you want to keep it alive."
          close-pr-message: ":no_entry: This pull request was closed because it has been inactive for 14 days since being marked as stale."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
